mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: dev
  application:
    name: mun
  datasource:
    url: jdbc:mysql://${mun.mysql.ip}:${mun.mysql.port}/${mun.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mun.mysql.username}
    password: ${mun.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver